"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os # Importante para ler variáveis de ambiente do EasyPanel

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# 1. CONFIGURAÇÕES GERAIS E SEGURANÇA
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r#4sg#ygc(&g7em3seei-lo79*3pfeo6f1w(t4hjs1cloc=88*'

# SECURITY WARNING: don't run with debug turned on in production!
# Mantemos True por enquanto para você ver erros se algo falhar na integração.
DEBUG = True

# Lista de domínios que o Django aceita servir.
ALLOWED_HOSTS = [
    'api.morenadoaco.com.br',  # Seu domínio de produção (EasyPanel)
    'localhost',               # Teste local
    '127.0.0.1'                # Teste local
]


# ==============================================================================
# 2. APLICATIVOS E MIDDLEWARE
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- LIBS DE TERCEIROS ---
    'corsheaders',             # Permite conexão do Frontend
    'rest_framework',          # API
    'rest_framework.authtoken',
    'rest_framework_simplejwt', # Autenticação JWT
    
    # --- SEUS APPS ---
    'app_estoque',             # Seu app principal
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <--- OBRIGATÓRIO: DEVE SER O PRIMEIRO
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================================================
# 3. BANCO DE DADOS (HÍBRIDO: LOCAL vs EASYPANEL)
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'controle_estoque',
        'USER': 'django_user',                
        'PASSWORD': '319Gj4T5Z%R9g,F3hh/Ea$q.|Pz&69!4',        # <--- COLOQUE SUA SENHA AQUI
        
        # LÓGICA INTELIGENTE:
        # 1. Tenta ler a variável 'DB_HOST' (que você configurará no EasyPanel).
        # 2. Se não encontrar (está no seu PC), usa '127.0.0.1'.
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        
        'PORT': '3306',
    }
}


#Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 4. ARQUIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'
# Pasta onde o Django reunirá os arquivos em produção (Obrigatório para EasyPanel)
STATIC_ROOT = BASE_DIR / 'staticfiles' 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração do Django REST Framework (JWT)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


# ==============================================================================
# 5. CONFIGURAÇÕES DE SEGURANÇA E CORS (CRUCIAL)
# ==============================================================================

# CORS: Quem pode acessar sua API?
CORS_ALLOWED_ORIGINS = [
    'https://faculdade.morenadoaco.com.br', # Seu Frontend no EasyPanel
    'http://127.0.0.1:5500',                # (Opcional) Testes locais
    'http://localhost:3000',                # (Opcional) Testes locais
]

# CSRF: Domínios confiáveis para o Django Admin
CSRF_TRUSTED_ORIGINS = [
    'https://api.morenadoaco.com.br',
    'https://faculdade.morenadoaco.com.br',
]

# PROXY SSL: Permite que o Django saiba que está rodando atrás do EasyPanel (HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True